version: '2'
services:
  sgp_db-postgresql:
    image: postgres:12.3

    environment:
      - POSTGRES_USER=SGP_DB
      - POSTGRES_PASSWORD=sgp
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
